src/SM.App/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using SM.Integration.Application.Interfaces;
using SM.Integration.Application.ViewModels;

namespace SM.App.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        // GET: CategoriaController
        public async Task<IActionResult> Index()
        {
            var categorias = await _categoryService.GetAllCategory();
            return View(categorias);
        }

        // GET: CategoriaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoriaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryViewModel categoryViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                var result = await _categoryService.AddCategory(categoryViewModel);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoriaController/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var resp = await _categoryService.GetCategoryById(id);
            return View(resp);
        }

        // POST: CategoriaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CategoryViewModel categoryViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                var result = await _categoryService.UpdateCategory(categoryViewModel);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/SM.App/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using SM.Integration.Application.Interfaces;
using SM.Integration.Application.ViewModels;

namespace SM.App.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        // GET: CustomerController
        public async Task<IActionResult> Index()
        {
            var Customers = await _customerService.GetAllCustomer();
            return View(Customers);
        }

        // GET: CustomerController/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            var Customer = await _customerService.GetCustomerById(id);
            return View(Customer);
        }

        // GET: CustomerController/Create
        public ActionResult Create()
        {
            var Customer = new CustomerViewModel
            {
                States = _customerService.GetAllStates()
            };
            return View(Customer);
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CustomerViewModel CustomerViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                var result = await _customerService.AddCustomer(CustomerViewModel);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CustomerController/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var Customer = await _customerService.GetCustomerById(id);
            Customer.States = _customerService.GetAllStates();
            return View(Customer);
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CustomerViewModel CustomerViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                var result = await _customerService.UpdateCustomer(CustomerViewModel);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/SM.App/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SM.App.Models;
using System.Diagnostics;

namespace SM.App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/SM.App/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using SM.Integration.Application.Htpp.Catalog;
using SM.Integration.Application.Interfaces;
using SM.Integration.Application.ViewModels;

namespace SM.App.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICatalogClient _catalogClient;

        public ProductController(IProductService productService, ICatalogClient catalogClient)
        {
            _productService = productService;
            _catalogClient = catalogClient;
        }

        // GET: ProductController
        public async Task<IActionResult> Index()
        {
            var product = await _productService.GetAllProduct();
            return View(product.OrderBy(p => p?.ResponseSupplierOut?.FantasyName));
        }

        // GET: ProductController/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            var product = await _catalogClient.GetProductById(id);
            return View(product);
        }

        // GET: ProductController/Create
        public async Task<IActionResult> Create()
        {
            var supplier = await _productService.GetAllSupplier();
            var category = await _catalogClient.GetAllCategory();
            var product = new ProductViewModel
            {
                SupplierViewModels = supplier.ToList(),
                CategoryViewModels = category.ToList()
            };

            return View(product);
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductViewModel productViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                productViewModel.PurchaseValue /= 100.0M;
                productViewModel.SaleValue /= 100.0M;
                productViewModel.ProfitMargin /= 100.0M;

                var result = await _productService.AddProduct(productViewModel);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var product = await _productService.GetProductById(id);

            var supplier = await _productService.GetAllSupplier();
            var category = await _catalogClient.GetAllCategory();
            product.SupplierViewModels = supplier.ToList();
            product.CategoryViewModels = category.ToList();

            return View(product);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductViewModel productViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                productViewModel.PurchaseValue /= 100.0M;
                productViewModel.SaleValue /= 100.0M;
                productViewModel.ProfitMargin /= 100.0M;

                var result = await _productService.UpdateProduct(productViewModel);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/SM.App/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Mvc;
using SM.Integration.Application.Interfaces;
using SM.Integration.Application.ViewModels;

namespace SM.App.Controllers
{
    public class SupplierController : Controller
    {
        private readonly ISupplierService _supplierService;

        public SupplierController(ISupplierService supplierService)
        {
            _supplierService = supplierService;
        }

        // GET: SupplierController
        public async Task<IActionResult> Index()
        {
            var suppliers = await _supplierService.GetAllSupplier();
            return View(suppliers);
        }

        // GET: SupplierController/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            var supplier = await _supplierService.GetSupplierById(id);
            return View(supplier);
        }

        // GET: SupplierController/Create
        public ActionResult Create()
        {
            var supplier = new SupplierViewModel
            {
                States = _supplierService.GetAllStates()
            };
            return View(supplier);
        }

        // POST: SupplierController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SupplierViewModel SupplierViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                var result = await _supplierService.AddSupplier(SupplierViewModel);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SupplierController/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var supplier = await _supplierService.GetSupplierById(id);
            supplier.States = _supplierService.GetAllStates();
            return View(supplier);
        }

        // POST: SupplierController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SupplierViewModel SupplierViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                var result = await _supplierService.UpdateSupplier(SupplierViewModel);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/SM.App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Loja Inspiração";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Dashboard</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-md-3 col-sm-6 col-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-success">
                            <img src="~/icones/bills-to-pay.png" />
                        </span>
                        <div class="info-box-content">
                            <a asp-controller="BillToPay" asp-action="Index" title="Contas a Pagar">
                                <span class="info-box-text">Contas a Pagar</span>
                            </a>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
                <!-- ./col -->
                <div class="col-md-3 col-sm-6 col-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-warning">
                            <img src="~/icones/customer.png" />
                        </span>
                        <div class="info-box-content">
                            <a asp-controller="Customer" asp-action="Index" title="Cliente">
                                <span class="info-box-text">Cliente</span>
                            </a>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
                <!-- ./col -->
                <div class="col-md-3 col-sm-6 col-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-success">
                            <img src="~/icones/cashier.png" />
                        </span>
                        <div class="info-box-content">
                            <span class="info-box-text">Caixa</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
                <!-- ./col -->
                <div class="col-md-3 col-sm-6 col-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-info">
                            <img src="~/icones/supplier.png" />
                        </span>
                        <div class="info-box-content">
                            <a asp-controller="Supplier" asp-action="Index" title="Fornecedor">
                                <span class="info-box-text">Fornecedor</span>
                            </a>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
                <!-- ./col -->
            </div>

            <div class="row">
                <div class="col-md-3 col-sm-6 col-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-info">
                            <img src="~/icones/product.png" />
                        </span>
                        <div class="info-box-content">
                            <a asp-controller="Product" asp-action="Index" title="Produto">
                                <span class="info-box-text">Produto</span>
                            </a>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>

                <!-- ./col -->
                <div class="col-md-3 col-sm-6 col-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-success">
                            <img src="~/icones/bills-to-receive.png" />
                        </span>
                        <div class="info-box-content">
                            <span class="info-box-text">Contas a Receber</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>

                <!-- ./col -->
                <div class="col-md-3 col-sm-6 col-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-danger">
                            <img src="~/icones/invoices.png" />
                        </span>
                        <div class="info-box-content">
                            <span class="info-box-text">Notas Fiscais</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>

                <!-- ./col -->
                <div class="col-md-3 col-sm-6 col-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-info">
                            <img src="~/icones/report.png" />
                        </span>
                        <div class="info-box-content">
                            <a asp-controller="Category" asp-action="Index" title="Consultar Categoria">
                                <span class="info-box-text">Categoria</span>
                            </a>
                        </div>
                    </div>
                    <!-- /.info-box -->
                </div>
                <!-- ./col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>