src/SM.App/Controllers/BillToPayController.cs
using Microsoft.AspNetCore.Mvc;
using SM.Integration.Application.Htpp.Financial;
using SM.Integration.Application.Htpp.People;
using SM.Integration.Application.Interfaces;
using SM.Integration.Application.ViewModels;

namespace SM.App.Controllers
{
    public class BillToPayController : Controller
    {
        private readonly IBillToPayService _billToPayService;
        private readonly IFinancialClient _financialClient;
        private readonly IPeopleClient _peopleClient;

        public BillToPayController(IBillToPayService billToPayService, IFinancialClient financialClient, IPeopleClient peopleClient)
        {
            _billToPayService = billToPayService;
            _financialClient = financialClient;
            _peopleClient = peopleClient;
        }

        // GET: BillToPayController
        public async Task<IActionResult> Index()
        {
            var bills = await _billToPayService.GetAllBillToPay();

            foreach (var item in bills)
                item.SupplierViewModel = await GetSupplierById(item.SupplierId);

            return View(bills);
        }

        // GET: BillToPayController/Create
        public async Task<IActionResult> Create()
        {
            var supplier = await _billToPayService.GetAllSupplier();
            var bill = new BillToPayViewModel
            {
                SupplierViewModels = supplier.ToList(),
            };

            return View(bill);
        }

        // POST: BillToPayController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BillToPayViewModel bill)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                bill.Value /= 100.0M;

                var result = await _billToPayService.AddBillToPay(bill);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        private async Task<SupplierViewModel> GetSupplierById(Guid id)
        {
            return await _peopleClient.GetSupplierById(id);
        }
    }
}

src/SM.App/Views/BillToPay/Create.cshtml
@model BillToPayViewModel

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Horizontal Form -->
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Cadastro de Contas a Pagar</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form asp-controller="BillToPay" asp-action="Create" class="form-horizontal" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="card-body">
                        <div class="form-group row d-none">
                            <label asp-for="Id" class="col-sm-2 col-form-label">Id</label>
                            <div class="col-sm-10">
                                <input asp-for="Id" class="form-control" placeholder="Id">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label asp-for="SupplierId" class="control-label"></label>
                                    <select asp-for="SupplierId" class="form-control" asp-items="@(new SelectList(Model.SupplierViewModels, "Id", "CorporateName"))">
                                        <option></option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="Description" class="control-label"></label>
                                    <input asp-for="Description" class="form-control" placeholder="Descrição">
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="DueDate" class="control-label"></label>
                                    <input asp-for="DueDate" class="form-control" placeholder="Data de Vencimento">
                                    <span asp-validation-for="DueDate" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="Value" class="control-label"></label>
                                    <input asp-for="Value" class="form-control" placeholder="Valor">
                                    <span asp-validation-for="Value" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-info">Salvar</button>
                        <a asp-action="Index" class="btn btn-default float-right">Voltar</a>
                    </div>
                    <!-- /.card-footer -->
                </form>
            </div>
            <!-- /.card -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function () {
            $('#DueDate').setMask({ mask: "99/99/9999" });
            $('#Value').setMask({ mask: '99.999.999.999.999', type: 'reverse' });

        });
    </script>
}

src/SM.App/Views/BillToPay/Index.cshtml
@model IEnumerable<BillToPayViewModel>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Lista de Contas a Pagar</h3>
                    <div style="text-align:right; margin-top: 10px">
                        <a asp-controller="BillToPay" asp-action="Create" class="btn btn-success"> Novo Cadastro</a>
                    </div>
                </div>
            </div>
            <div class="card">

                <!-- /.card-header -->
                <div class="card-body p-0">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th class="d-none">
                                    @Html.DisplayNameFor(model => model.Id)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.SupplierId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Description)
                                </th>
                                <th style="text-align:center;">
                                    @Html.DisplayNameFor(model => model.DueDate)
                                </th>
                                <th style="text-align:center;">
                                    @Html.DisplayNameFor(model => model.Value)
                                </th>
                                <th style="text-align:center;">
                                    @Html.DisplayNameFor(model => model.Status)
                                </th>
                                <th>Ações</th>
                            </tr>
                        </thead>

                        <tbody>
                            @if (Model != null)
                            {
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="d-none">
                                            @Html.DisplayFor(modelItem => item.Id)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.SupplierViewModel.FantasyName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Description)
                                        </td>
                                        <td style="text-align:center;">
                                            @Html.DisplayFor(modelItem => item.DueDate)
                                        </td>
                                        <td style="text-align:right;">
                                            @Html.DisplayFor(modelItem => item.Value)
                                        </td>
                                        <td style="text-align:center;">
                                            @Html.DisplayFor(modelItem => item.Situacao)
                                        </td>
                                        <td>
                                            <a asp-controller="BillToPay" asp-action="Edit" asp-route-id="@item.Id">
                                                <i class="bi bi-pencil-square btn btn-primary" aria-hidden="true" title="Editar"></i>
                                            </a>
                                            <a asp-controller="BillToPay" asp-action="Details" asp-route-id="@item.Id">
                                                <i class="bi bi-ticket-detailed btn btn-info" aria-hidden="true" title="Details"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->

        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>